# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lrn_profile.ui',
# licensing of 'lrn_profile.ui' applies.
#
# Created: Thu May 30 15:09:02 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 170, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 170, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 170, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 127, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Form.setPalette(palette)
        Form.setAutoFillBackground(True)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 641, 101))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(30)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.EditProf = QtWidgets.QPushButton(Form)
        self.EditProf.setGeometry(QtCore.QRect(620, 500, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.EditProf.setFont(font)
        self.EditProf.setObjectName("EditProf")
        self.Go_back = QtWidgets.QPushButton(Form)
        self.Go_back.setGeometry(QtCore.QRect(620, 610, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Go_back.setFont(font)
        self.Go_back.setObjectName("Go_back")
        self.Fname_title = QtWidgets.QLabel(Form)
        self.Fname_title.setGeometry(QtCore.QRect(30, 170, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname_title.setFont(font)
        self.Fname_title.setObjectName("Fname_title")
        self.Fname_2 = QtWidgets.QLabel(Form)
        self.Fname_2.setGeometry(QtCore.QRect(30, 230, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname_2.setFont(font)
        self.Fname_2.setObjectName("Fname_2")
        self.Fname_3 = QtWidgets.QLabel(Form)
        self.Fname_3.setGeometry(QtCore.QRect(30, 110, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname_3.setFont(font)
        self.Fname_3.setObjectName("Fname_3")
        self.Fname_4 = QtWidgets.QLabel(Form)
        self.Fname_4.setGeometry(QtCore.QRect(30, 290, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname_4.setFont(font)
        self.Fname_4.setObjectName("Fname_4")
        self.Fname_5 = QtWidgets.QLabel(Form)
        self.Fname_5.setGeometry(QtCore.QRect(30, 420, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname_5.setFont(font)
        self.Fname_5.setObjectName("Fname_5")
        self.Fname_6 = QtWidgets.QLabel(Form)
        self.Fname_6.setGeometry(QtCore.QRect(30, 350, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname_6.setFont(font)
        self.Fname_6.setObjectName("Fname_6")
        self.Fname_7 = QtWidgets.QLabel(Form)
        self.Fname_7.setGeometry(QtCore.QRect(30, 610, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname_7.setFont(font)
        self.Fname_7.setObjectName("Fname_7")
        self.Fname_8 = QtWidgets.QLabel(Form)
        self.Fname_8.setGeometry(QtCore.QRect(30, 540, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname_8.setFont(font)
        self.Fname_8.setObjectName("Fname_8")
        self.Fname_9 = QtWidgets.QLabel(Form)
        self.Fname_9.setGeometry(QtCore.QRect(30, 480, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname_9.setFont(font)
        self.Fname_9.setObjectName("Fname_9")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(650, 310, 391, 181))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(100)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"color: rgb(0, 255, 150);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(650, 20, 441, 321))
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(150)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("QLabel {\n"
"color: rgb(0, 255, 150);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.Uname = QtWidgets.QLabel(Form)
        self.Uname.setGeometry(QtCore.QRect(230, 110, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Uname.setFont(font)
        self.Uname.setObjectName("Uname")
        self.Fname = QtWidgets.QLabel(Form)
        self.Fname.setGeometry(QtCore.QRect(230, 170, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Fname.setFont(font)
        self.Fname.setObjectName("Fname")
        self.Lname = QtWidgets.QLabel(Form)
        self.Lname.setGeometry(QtCore.QRect(230, 230, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Lname.setFont(font)
        self.Lname.setObjectName("Lname")
        self.Sex = QtWidgets.QLabel(Form)
        self.Sex.setGeometry(QtCore.QRect(230, 290, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Sex.setFont(font)
        self.Sex.setObjectName("Sex")
        self.Email = QtWidgets.QLabel(Form)
        self.Email.setGeometry(QtCore.QRect(230, 350, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Email.setFont(font)
        self.Email.setObjectName("Email")
        self.Phone = QtWidgets.QLabel(Form)
        self.Phone.setGeometry(QtCore.QRect(230, 420, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Phone.setFont(font)
        self.Phone.setObjectName("Phone")
        self.Tag = QtWidgets.QLabel(Form)
        self.Tag.setGeometry(QtCore.QRect(230, 480, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Tag.setFont(font)
        self.Tag.setObjectName("Tag")
        self.Type = QtWidgets.QLabel(Form)
        self.Type.setGeometry(QtCore.QRect(230, 540, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Type.setFont(font)
        self.Type.setObjectName("Type")
        self.Pref = QtWidgets.QLabel(Form)
        self.Pref.setGeometry(QtCore.QRect(230, 610, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.Pref.setFont(font)
        self.Pref.setObjectName("Pref")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Learner\'s Profile", None, -1))
        self.EditProf.setText(QtWidgets.QApplication.translate("Form", "Edit Profile", None, -1))
        self.Go_back.setText(QtWidgets.QApplication.translate("Form", "Go back", None, -1))
        self.Fname_title.setText(QtWidgets.QApplication.translate("Form", "First Name:", None, -1))
        self.Fname_2.setText(QtWidgets.QApplication.translate("Form", "Last Name:", None, -1))
        self.Fname_3.setText(QtWidgets.QApplication.translate("Form", "User Name:", None, -1))
        self.Fname_4.setText(QtWidgets.QApplication.translate("Form", "Gender:", None, -1))
        self.Fname_5.setText(QtWidgets.QApplication.translate("Form", "Phone No:", None, -1))
        self.Fname_6.setText(QtWidgets.QApplication.translate("Form", "Email:", None, -1))
        self.Fname_7.setText(QtWidgets.QApplication.translate("Form", "Preference: ", None, -1))
        self.Fname_8.setText(QtWidgets.QApplication.translate("Form", "Type:", None, -1))
        self.Fname_9.setText(QtWidgets.QApplication.translate("Form", "Tags:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "skill", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "UP", None, -1))
        self.Uname.setText(QtWidgets.QApplication.translate("Form", "uname", None, -1))
        self.Fname.setText(QtWidgets.QApplication.translate("Form", "Fname", None, -1))
        self.Lname.setText(QtWidgets.QApplication.translate("Form", "Lname", None, -1))
        self.Sex.setText(QtWidgets.QApplication.translate("Form", "Sex", None, -1))
        self.Email.setText(QtWidgets.QApplication.translate("Form", "Email", None, -1))
        self.Phone.setText(QtWidgets.QApplication.translate("Form", "Phone", None, -1))
        self.Tag.setText(QtWidgets.QApplication.translate("Form", "Tag", None, -1))
        self.Type.setText(QtWidgets.QApplication.translate("Form", "Type", None, -1))
        self.Pref.setText(QtWidgets.QApplication.translate("Form", "Pref", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

