# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Viewcourseenroll.ui',
# licensing of 'Viewcourseenroll.ui' applies.
#
# Created: Wed May 29 14:52:07 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 580, 281, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 580, 281, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(760, 580, 281, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.Pref = QtWidgets.QLineEdit(Form)
        self.Pref.setGeometry(QtCore.QRect(40, 50, 331, 481))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.Pref.setFont(font)
        self.Pref.setObjectName("Pref")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(410, 200, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(620, 130, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(410, 120, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(410, 280, 681, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(620, 210, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(620, 290, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(620, 360, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(620, 430, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("Form", "View Profile", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("Form", "Go back", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("Form", "Enroll", None, -1))
        self.Pref.setText(QtWidgets.QApplication.translate("Form", "Logo/Picture", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Speaker: ", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "This is the course name", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "Name:", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "Description:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Arjan John Johnson", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "This course will teach you the way of Life", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "and how to become a successful owner", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "of the most beautiful restaurant", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

